### PR TITLE
Rename LICENCE.txt to LICENCE

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**

### CODE REVIEW

**Comment by knocte** [comment]
Why? If I merge this, I cannot double-click the file in Windows and open it directly.

**Comment by ShubhamTatvamasi** [comment]
Oh okay, if you merge it then it will show your licence in your github repo on top.

**Comment by knocte** [comment]
It already shows the license at the top without the need of renaming, have a more careful look ;-)

**Comment by ShubhamTatvamasi** [comment]
Cool, just saw it, I think it was not showing before.

**Comment by knocte** [comment]
It was definitely showing before.

**Pull request closed without merging**
